filename='SunbeamSPADV8b.dat';
SPADID = fopen(filename,'w');
fprintf(SPADID,'%-20s %2s %-20s \n','Version',':','8b');
fprintf(SPADID,'%-20s %2s %-20s \n','System',':','Sunbeam');
fprintf(SPADID,'%-20s %2s %-20s \n','Analysis Type',':','Area');
fprintf(SPADID,'%-20s %2s %-20s \n','Current time',':',datetime);
fprintf(SPADID,'\n');
fprintf(SPADID,'\n');
fprintf(SPADID,'%-10s %2s %-1d \n','Motion',':',1);
fprintf(SPADID,'  %-8s %2s %-7s \n','Name',':','Azimuth');
fprintf(SPADID,'  %-8s %2s %-7s \n','Method',':','Step');
fprintf(SPADID,'  %-8s %2s %-3d \n','Minimum',':',-180);
fprintf(SPADID,'  %-8s %2s %-3d \n','Maximum',':',180);
fprintf(SPADID,'  %-8s %2s %-1d \n','Step',':',5);
fprintf(SPADID,'%-10s %2s %-1d \n','Motion',':',2);
fprintf(SPADID,'  %-8s %2s %-7s \n','Name',':','Elevation');
fprintf(SPADID,'  %-8s %2s %-7s \n','Method',':','Step');
fprintf(SPADID,'  %-8s %2s %-3d \n','Minimum',':',-90);
fprintf(SPADID,'  %-8s %2s %-3d \n','Maximum',':',90);
fprintf(SPADID,'  %-8s %2s %-1d \n','Step',':',5);
fprintf(SPADID,'%5s \n',': END');
fprintf(SPADID,'\n');
fprintf(SPADID,'%12s %1s %5d \n','Record count',':',length(SPAD_matrix));
fprintf(SPADID,'%-10s %-7s %-18s %-18s %-18s \n','Azimuth','Elevation','Force(X)','Force(Y)','Force(Z)');
fprintf(SPADID,'%10s %7s %18s %18s %18s \n','degrees','degrees','m^2','m^2','m^2');
fprintf(SPADID,'%-10s %-7s %-18s %-18s %-18s \n','----------','-------','------------------','------------------','------------------');
fprintf(SPADID,'%10.2f %7.2f %18.14f %18.14f %18.14f \n',SPAD_matrix.');
fclose(SPADID);